var USAhistory = [ {
    "id" : "us_general",
    "title" : "American History",
    "description" : "",
    "focus_date" : "1900-06-01 2:00:00",
    "initial_zoom" : "54",
    "size_importance" : "1",
    "inverted" : true,
    "bottom" : 200,
    "events" : [
            {
                "id" : "tg_line_befecbb76b6beef453ae53345a44315e816470",
                "title" : "Revolutionary War",
                "startdate" : "1775-04-19 17:00",
                "enddate" : "1783-09-03 17:00",
                "date_display" : "da",
                "icon" : "triangle_red.png",
                "low_threshold" : "0",
                "high_threshold" : "60",
                "importance" : "60",
                "y_position" : "0",
                "modal_type" : "default"
            },
            {
                "id" : "warof1812",
                "title" : "War of 1812",
                "startdate" : "1812-06-18 17:00",
                "enddate" : "1815-02-18 17:00",
                "date_display" : "da",
                "link" : "http://en.m.wikipedia.org/wiki/War_of_1812",
                "icon" : "triangle_red.png",
                "low_threshold" : "0",
                "high_threshold" : "60",
                "importance" : "55",
                "y_position" : "0",
                "modal_type" : "default"
            },
            {
                "id" : "tg_line_befecbb76b6beef453ae53345a44315e816465",
                "title" : "The Civil War",
                "startdate" : "1861-04-12 17:00",
                "enddate" : "1865-04-09 17:00",
                "date_display" : "da",
                "description" : "",
                "link" : "http://en.m.wikipedia.org/wiki/American_Civil_War",
                "icon" : "triangle_red.png",
                "low_threshold" : "0",
                "high_threshold" : "60",
                "importance" : "60",
                "y_position" : "0",
                "modal_type" : "default"
            },
            {
                "id" : "end_slavery",
                "title" : "Amendment XIII",
                "startdate" : "1865-12-06 17:00",
                "enddate" : "1865-12-06 17:00",
                "date_display" : "da",
                "description" : "Section 1. Slavery prohibited.<br/>Neither slavery nor involuntary servitude, except as a punishment for crime whereof the party shall have been duly convicted, shall exist within the United States, or any place subject to their jurisdiction.",
                "link" : "http://en.wikipedia.org/wiki/Thirteenth_Amendment_to_the_United_States_Constitution",
                "icon" : "triangle_green.png",
                "low_threshold" : "0",
                "high_threshold" : "60",
                "importance" : "55",
                "y_position" : "0",
                "modal_type" : "default"
            },
            {
                "id" : "tg_line_befecbb76b6beef453ae53345a44315e816472",
                "title" : "Reconstruction Era",
                "startdate" : "1863-06-01 17:00",
                "enddate" : "1877-06-01 17:00",
                "date_display" : "ye",
                "description" : "",
                "link" : "",
                "icon" : "triangle_blue.png",
                "low_threshold" : "0",
                "high_threshold" : "60",
                "importance" : "55",
                "y_position" : "0",
                "modal_type" : "default"
            },
            {
                "id" : "tg_line_befecbb76b6beef453ae53345a44315e816473",
                "title" : "Wright Brothers' First Flight",
                "startdate" : "1903-12-17 17:00",
                "enddate" : "1903-12-17 17:00",
                "date_display" : "da",
                "description" : "",
                "link" : "http://en.m.wikipedia.org/wiki/Wright_Flyer",
                "icon" : "triangle_green.png",
                "low_threshold" : "0",
                "high_threshold" : "60",
                "importance" : "55",
                "y_position" : "0",
                "modal_type" : "default"
            },
            {
                "id" : "tg_line_befecbb76b6beef453ae53345a44315e816464",
                "title" : "World War I",
                "startdate" : "1914-07-14 17:00",
                "enddate" : "1918-11-11 17:00",
                "date_display" : "da",
                "description" : "",
                "link" : "",
                "icon" : "triangle_red.png",
                "low_threshold" : "0",
                "high_threshold" : "60",
                "importance" : "60",
                "y_position" : "0",
                "modal_type" : "default"
            }

            ,
            {
                "id" : "tg_line",
                "title" : "Black Monday: Wall Street Crash",
                "startdate" : "1929-10-28 17:00",
                "date_display" : "da",
                "description" : "",
                "link" : "http://en.m.wikipedia.org/wiki/Wall_Street_Crash_of_1929",
                "icon" : "triangle_black.png",
                "low_threshold" : "0",
                "high_threshold" : "45",
                "importance" : "50",
                "y_position" : "0",
                "modal_type" : "default"
            }

            ,
            {
                "id" : "tg_fdr_elected",
                "title" : "FDR Elected",
                "startdate" : "1932-11-01 17:00",
                "date_display" : "mo",
                "link" : "http://en.m.wikipedia.org/wiki/Franklin_D._Roosevelt",
                "icon" : "triangle_blue.png",
                "low_threshold" : "0",
                "high_threshold" : "45",
                "importance" : "40",
                "y_position" : "0",
                "modal_type" : "default"
            }

            ,
            {
                "id" : "tg_line_befecbb76b6beef453ae53345a44315e816471",
                "title" : "The Great Depression",
                "startdate" : "1929-09-04 17:00",
                "enddate" : "1939-09-04 17:00",
                "date_display" : "ye",
                "description" : "",
                "link" : "http://en.m.wikipedia.org/wiki/Great_Depression",
                "icon" : "triangle_gray.png",
                "low_threshold" : "0",
                "high_threshold" : "60",
                "importance" : "60",
                "y_position" : "0",
                "modal_type" : "default"
            }

            ,
            {
                "id" : "dustbowl",
                "title" : "The Dust Bowl",
                "startdate" : "1933-06-01 17:00",
                "enddate" : "1936-10-01 17:00",
                "date_display" : "mo",
                "description" : "",
                "link" : "http://en.m.wikipedia.org/wiki/Dustbowl",
                "icon" : "triangle_gray.png",
                "low_threshold" : "0",
                "high_threshold" : "45",
                "importance" : "50",
                "y_position" : "0",
                "modal_type" : "default"
            }

            ,
            {
                "id" : "tg_line_befecbb76b6beef453ae53345a44315e816463",
                "title" : "The U.S. in World War II",
                "startdate" : "1941-12-07 17:00",
                "enddate" : "1945-09-02 17:00",
                "date_display" : "da",
                "description" : "",
                "link" : "",
                "icon" : "triangle_red.png",
                "low_threshold" : "0",
                "high_threshold" : "60",
                "importance" : "60",
                "y_position" : "0",
                "modal_type" : "default"
            },
            {
                "id" : "tg_line_befecbb76b6beef453ae53345a44315e816474",
                "title" : "Atom bombs dropped on Hiroshima and Nagasaki",
                "startdate" : "1945-08-06 17:00",
                "enddate" : "1945-08-09 17:00",
                "date_display" : "da",
                "description" : "",
                "link" : "http://en.m.wikipedia.org/wiki/Atomic_bombings_of_Hiroshima_and_Nagasaki",
                "icon" : "triangle_black.png",
                "low_threshold" : "0",
                "high_threshold" : "60",
                "importance" : "55",
                "y_position" : "0",
                "modal_type" : "default"
            },
            {
                "id" : "tg_line_befecbb76b6beef453ae53345a44315e816466",
                "title" : "Korean War",
                "startdate" : "1950-06-25 17:00",
                "enddate" : "1953-07-27 17:00",
                "date_display" : "da",
                "description" : "",
                "link" : "http://en.m.wikipedia.org/wiki/Korean_War",
                "icon" : "triangle_red.png",
                "low_threshold" : "0",
                "high_threshold" : "60",
                "importance" : "55",
                "y_position" : "0",
                "modal_type" : "default"
            }

            ,
            {
                "id" : "suffrage",
                "title" : "Women's Suffrage Movement",
                "startdate" : "1848-07-20 17:00",
                "enddate" : "1920-08-26 17:00",
                "date_display" : "ye",
                "link" : "http://en.m.wikipedia.org/wiki/Women's_suffrage",
                "icon" : "triangle_green.png",
                "low_threshold" : "0",
                "high_threshold" : "60",
                "importance" : "50",
                "modal_type" : "default"
            }

            ,
            {
                "id" : "civil_rights_era",
                "title" : "Civil Rights Era",
                "startdate" : "1955-01-01 17:00",
                "enddate" : "1968-12-31 17:00",
                "date_display" : "ye",
                "link" : "http://en.m.wikipedia.org/wiki/African-American_Civil_Rights_Movement_(1955%E2%80%931968)",
                "icon" : "triangle_green.png",
                "low_threshold" : "0",
                "high_threshold" : "60",
                "importance" : "50",
                "y_position" : "0",
                "modal_type" : "default"
            }, {
                "id" : "tg_line_befecbb76b6beef453ae53345a44315e816468",
                "title" : "Vietnam War",
                "startdate" : "1955-11-01 17:00",
                "enddate" : "1975-04-30 17:00",
                "date_display" : "da",
                "description" : "",
                "link" : "http://en.m.wikipedia.org/wiki/Vietnam_War",
                "icon" : "triangle_red.png",
                "low_threshold" : "0",
                "high_threshold" : "60",
                "importance" : "60",
                "y_position" : "0",
                "modal_type" : "default"
            }, {
                "id" : "tg_line_befecbb76b6beef453ae53345a44315e816469",
                "title" : "Gulf War",
                "startdate" : "1990-08-02 17:00",
                "enddate" : "1991-02-28 17:00",
                "date_display" : "da",
                "description" : "",
                "link" : "http://en.m.wikipedia.org/wiki/Gulf_War",
                "icon" : "triangle_red.png",
                "low_threshold" : "0",
                "high_threshold" : "60",
                "importance" : "52",
                "y_position" : "0",
                "modal_type" : "default"
            }, {
                "id" : "tg_line_befecbb76b6beef453ae53345a44315e816478",
                "title" : "War in Afghanistan",
                "startdate" : "2001-09-07 17:00",
                "enddate" : "2012-05-18 17:00",
                "date_display" : "da",
                "description" : "",
                "link" : "",
                "icon" : "triangle_red.png",
                "low_threshold" : "0",
                "high_threshold" : "60",
                "importance" : "55",
                "y_position" : "0",
                "modal_type" : "default"
            }, {
                "id" : "tg_line_befecbb76b6beef453ae53345a44315e816479",
                "title" : "September 11 Attacks",
                "startdate" : "2001-09-11 13:30",
                "enddate" : "2001-09-11 13:30",
                "date_display" : "da",
                "description" : "",
                "link" : "http://en.m.wikipedia.org/wiki/September_11_attacks",
                "icon" : "triangle_black.png",
                "low_threshold" : "0",
                "high_threshold" : "60",
                "importance" : "53",
                "y_position" : "0",
                "modal_type" : "default"
            }, {
                "id" : "tg_line_befecbb76b6beef453ae53345a44315e816476",
                "title" : "Iraq War",
                "startdate" : "2003-03-20 17:00",
                "enddate" : "2011-12-15 17:00",
                "date_display" : "da",
                "description" : "",
                "link" : "http://en.m.wikipedia.org/wiki/Iraq_War",
                "icon" : "triangle_red.png",
                "low_threshold" : "0",
                "high_threshold" : "60",
                "importance" : "55",
                "y_position" : "0",
                "modal_type" : "default"
            } ]
} ]